name: CI

on:
  push:
    branches:
      - proj/my-tiny-stl
  pull_request:
    branches:
      - proj/my-tiny-stl
  workflow_dispatch:
    branches:
      - proj/my-tiny-stl

jobs:
  build_and_test:
    name: Build & test on ${{ matrix.os }} with ${{ matrix.compiler }}.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [ g++-10 ]
        include:
          - os: ubuntu-latest
            compiler: g++-10
            target: Linux

          - os: macos-latest
            compiler: g++-10
            target: Macos

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - run: |-
          mkdir build && cd ./build
          cmake ..
          make
          cd ../bin && ./stltest
