name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build & test on ${{ matrix.os }}.
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - run: |-
          sudo ./scripts/init-env.sh Release
          mkdir build && cd ./build
          cmake ..
          make
          cd ../build && ./*_test
