name: CI

on:
  push:
    branches:
      - proj/my-tiny-stl
  pull_request:
    branches:
      - proj/my-tiny-stl
  workflow_dispatch:
    branches:
      - proj/my-tiny-stl

jobs:
  build_and_test:
    name: Build & test on ${{ matrix.os }} with ${{ matrix.compiler }}.
    strategy:
      matrix:
        os:
          - linux
          - osx
        compiler:
          - g++-8
          - clang++-8
          - g++-12
          - clang++-12
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - run: |-
          mkdir build && cd ./build
          cmake ..
          make
          cd ../bin && ./stltest
        shell: bash
        env:
          - name: CXX
            value: ${{ matrix.compiler }}
          - name: CC
            value: ${{ matrix.compiler }}
          - name: CMAKE_CXX_COMPILER
            value: ${{ matrix.compiler }}
          - name: CMAKE_C_COMPILER
            value: ${{ matrix.compiler }}
